import type { Metadata } from "next";
import { ReduxProvider } from "@/redux/Provider";
import LanguageSwitcher from "@/components/LanguageSwitcher";
import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable}antialiased`}>
        <ReduxProvider>
          <LanguageSwitcher />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
